project:
  type: website
  output-dir: docs
  

website:
  title: "Environmental Data Science"
  navbar:
    search: true
    background: light
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd
    tools:
      - icon: github
        href: https://github.com/romero61
      - icon: linkedin
        href: https://www.linkedin.com/in/romero61/
      - icon: envelope-exclamation
        href: mailto:romero61@bren.ucsb.edu
format:
  html:
    theme: 
      light: lux
      dark: cyborg
    css: styles.css
    toc: true

editor: visual

