project:
  type: website
  output-dir: docs

website:
  title: "Guillermo Romero"
  navbar:
    search: true
    background: light
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd
format:
  html:
    theme: 
      dark: cyborg
      light: lux
    css: styles.css
    toc: true

editor: visual

