---
title: "resume"
editor: visual
---

[View and Download Resume Here](Romero_Guillermo.pdf){style="color: red"}

# EDUCATION

### **Master of Data Science in Environmental Data Science**

(June 2023)

**Bren School Of Environmental Science & Management - University of California, Santa Barbara**

> Highlighted Coursework: Machine Learning in Environmental Science, Databases and Data Management, Modeling Environmental Systems, Statistics for Environmental Data Science (All to be completed by June 2023)

### **Bachelor of Science in Earth Science -- Geohydrology Emphasis**

### **Bachelor of Arts in Geography -- Geographic Information Systems (GIS) Emphasis**

(June 2022)

**University of California, Santa Barbara**

> Honors/Awards: UCSB Scholarship, Outstanding Achievement in the Geography Major
>
> Highlighted Coursework:
>
> Remote Sensing- Advanced image processing, including data fusion and resampling techniques, atmospheric corrections, global navigation satellite systems, and hyperspatial sensors with emphasis on applications.
>
> Ocean Remote Sensing- Physical principles and tools required for processing active and passive remote sensing data for coastal and ocean applications. Topics include remote sensing of phytoplankton, sea surface temperature, ocean winds and currents, and sea ice. Lab includes analysis of optical, thermal infrared, passive microwave, and radar data.
>
> Awarded UCSB Scholarship, Outstanding Achievement in the Geography Major

# SKILLS

------------------------------------------------------------------------

**Languages**: Python (GeoPandas, Rasterio, Sci-kit), Spanish, R (Tidyverse, SF, Terra), Markdown, SQL, MATLAB

**Environments**: VSCode, Jupyter Notebook, Google Earth Engine, GitHub, RStudio, Quarto, ArcGIS Pro, QGIS

**Technical**: Exploratory Data Analysis (EDA), Data Visualization, Machine Learning,Technical Writing of Environmental Field Work

## Master's Capstone Project - Informing Forest Conservation Regulations in Paraguay (1/22--Present)

Client: Paraguay --- National Forestry Institute; UCSB --- Dr. Robert Heilmayr \| Role: Machine Learning Engineer

-   Applied machine learning techniques by creating a Random Forest model in Python to predict future deforestation patterns and generate pixel-wise probabilities of imminent deforestation.

-    Developed a data acquisition and preprocessing pipeline with Google Earth Engine and Python, supporting large-scale geospatial data analysis and enhancing the accuracy of deforestation predictions.

-   Estimated protected forest area under different regulations by developing a law-based geospatial simulation tool in R. This tool facilitated a comparison between the most and least stringent regulations, revealing a difference of 3,397,183 ha in the undeveloped Chaco region.

-   Utilized geospatial overlays for a comprehensive assessment of land use plan compliance and deforestation rates in the Paraguayan Chaco, discovering 44% of the deforestation occurred in protected areas and was considered unauthorized, totaling 21,321 ha of illegal deforestation.

-   Enhanced stakeholder engagement & decision-making by providing an interactive Shiny dashboard for examining results, serving as a crucial tool for informed policy making on forest conservation and land use.

## GEOSPATIAL & DATA SCIENCE PROJECTS

### Burn Severity with Sentinel-2 data using Google Earth Engine \| Working with Environmental Data (12/22)

-   Conducted burn severity analysis of the August Complex Fire, utilizing Sentinel-2 Image Collection and MTBS Feature Collection.

-   Developed a processing and visualization pipeline for the difference normalized burn ratio (DNBR) by severity class using Google Earth Engine and Python.

-   Leveraged the GEE platform to efficiently process and analyze large-scale satellite data.

### Statistical Analysis of NDVI in Redlined Regions \| Statistics for Environmental Data Science (11/22)

-   Managed data wrangling and exploratory data analysis (EDA) in R, leading to a cleaner, more organized dataset for analysis.

-   Applied Log-Log Ordinary Least Squares Regression & hypothesis testing for a comprehensive statistical analysis of NDVI data in redlined regions, highlighting non-linear relationships and informing urban planning policies.

-   Interpreted regression coefficients to provide insights on the impact of individual variables, which can influence decisions or policies.

### Analyzing Greenness through NDVI in Redlined areas in Philadelphia, PA \| Undergraduate Thesis (4/22--6/22)

-   Preprocessed Landsat 8 OLI satellite data using RStudio for NDVI calculations, resulting in a comprehensive understanding of greenness levels in redlined area.

-   Conducted QGIS processing for NDVI and zonal statistics calculation, supporting the development of environmental improvement strategies.

-   Integrated census median income, NDVI, and Redline data through QGIS and Excel, providing a multifaceted view of socio-economic and environmental factors in redlined areas.

### Logistics Experience

------------------------------------------------------------------------

##### General Warehouse Worker -- Best Buy, Los Angeles, CA (9/18/-9/21)

-   Ensures daily home deliveries for all Southern California locations are correctly loaded.

-   Safeguard that defective and returned products are accurately processed and prepped for relocation.

-   Routes orders by locating the specified product and moving it to the loading dock

##### SWAT Inventory Specialist -- Best Buy, Los Angeles, CA (5/2010 -- 11/2015)

-   Responsible for counting assigned product counts, entering counts into RSS, researching variances, and reporting discrepancies to management. Oversaw and prepared for annual physical inventory and assisted in post physical inventory reconciliation.

-   Supported senior management by delivering reports outlining performance to drive process improvements.

-   Coached employees around shrink trends and behaviors by communicating and coaching store employees and leadership on the importance of inventory integrity and any identified process gaps)

### Additional Education

##### El Camino Community College

##### (June 2020)

El Camino College Foundation - Scholarship

Associate of Science in Physics for Transfer

Associate of Science in Mathematics for Transfer

Associate of Science in General Science -- Honors

Associate of Arts in General Arts - Honors Associate of Arts in General Studies Biology and Physical Science

### CERTIFICATIONS

------------------------------------------------------------------------

● Recording Connection - Recording Engineer Certificate

● OSHA - Forklift Certification
